spring.application.name=bookhub-backend

# Connexion à la base de données
spring.datasource.url=jdbc:sqlserver://localhost;databasename=BOOKHUB;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd