spring.application.name=bookhub-backend
#
## Connexion à la base de données
#spring.datasource.url=jdbc:
#spring.datasource.username=sa
#spring.datasource.password=Pa$$w0rd

spring.datasource.url=jdbc:postgresql://localhost:5432/BOOKHUB
spring.datasource.username=postgres
spring.datasource.password=bookhub123
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=une-cle-vraiment-longue-et-aleatoire-de-256bits-minimum
jwt.expiration=86400000